services:
    - type: web
      name: CammionControlApp
      env: node
      plan: free
      rootDirectory: backend
      buildCommand: npm run build
      startCommand: npm start
      envVars:
          - key: NODE_ENV
            value: production
